parameters:
    batch_size: 8
    num_updates: 5
    num_rounds: 20
    dataset_size: 100
    test_dataset_size: 100
    max_sample: 5
    num_trainings: 20
    num_centers: 5
    abs_detection_treshold: 1e-7
    rel_detection_treshold: 1e-2  
    num_hidden_neurons: 1000 # 28*28 = 784
    dataset: dna
    num_exp_repeat: 10
    seed: 42
    n_jobs: 1
    prun_risky_rel_lambda_threshold: 0
    prun_risky_update_threshold: 0
    use_kmeans_for_clustering: False
    split_with_dirichlet: False
    dirichlet_param: 10.

    lr: 
        type: 'log'
        min: -2
        max: 0

experiment:
    dataset_folder: ./datasets
    temp_directory_location: ./temp
    log_data: False
    experiment_name: dna_beta_defended
    run_name: dna_beta0
    save_dir: ./mlflow/mlruns