name: Linting

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7",]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install isort
        pip install flake8
    - name: Analysing the code with black
      run: |
        black --check --line-length=88 .
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length=88 --per-file-ignores=*/__init__.py:F401 --ignore=W503,E203,E501
    - name: Analysing the code with isort
      run: |
       isort --profile black --filter-files --line-length 88 --check .
